### PR TITLE
update hugo to 0.107.0

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/tektoncd/website/issues/514

### CODE REVIEW

**Comment by Arhell** [comment]
cc @geriom

**Review by geriom — CHANGES_REQUESTED** [review]
@Arhell Checking the [release notes](https://github.com/gohugoio/hugo/releases/tag/v0.110.0),  it seems this version of hugo requires `config.yaml` to be renamed to `hugo.yaml` .  Can you please rename the file?

**Comment by Arhell** [comment]
> @Arhell Checking the [release notes](https://github.com/gohugoio/hugo/releases/tag/v0.110.0), it seems this version of hugo requires `config.yaml` to be renamed to `hugo.yaml` . Can you please rename the file?

Done

**Comment by geriom** [comment]
> Done

The renamed file `netlfy.toml -> hugo.toml`, is not the correct one.  It should be `config.yaml -> hugo.yaml`.

**Comment by Arhell** [comment]
> > Done
> 
> The renamed file `netlfy.toml -> hugo.toml`, is not the correct one. It should be `config.yaml -> hugo.yaml`.

oh yes, corrected

**Comment by geriom** [comment]
Thank you for the update @Arhell 

This is a breaking change, anyone running the website locally will have to update their hugo version, which is particularly a problem if you run it inside a container. Currently the latest version of the base hugo image we use is [107](https://github.com/klakegg/docker-hugo/releases). 

Since this is not urgent maybe we can wait until that repo catches up with hugo, or we can use a different docker image.

**Comment by Arhell** [comment]
> Thank you for the update @Arhell
> 
> This is a breaking change, anyone running the website locally will have to update their hugo version, which is particularly a problem if you run it inside a container. Currently the latest version of the base hugo image we use is [107](https://github.com/klakegg/docker-hugo/releases).
> 
> Since this is not urgent maybe we can wait until that repo catches up with hugo, or we can use a different docker image.

Updated PR to 107v

**Review by geriom — COMMENTED** [review]
Thank you!

**Review by geriom — APPROVED** [review]

**Pull request merged**
