### PR TITLE
Katacoda scenario Using Tekton Tasks - Python 3.10

### PR DESCRIPTION
**Pull request by vovtz**
# Changes
Make Katacoda scenario “Using Tekton Tasks” compatible with Python 3.10: https://github.com/tektoncd/website/issues/349

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by AlanGreene** [comment]
Since https://github.com/tektoncd/website/pull/348 pinned the image version to python:3.9 do we need to update this?

I'm not sure if we really want to continually update the packages since they're not the primary purpose/focus of the tutorial. Pinning to a known working version should be enough. I suspect we'll be rewriting these tutorials as part of our updated documentation strategy, to focus more on the core goals of the tutorial (e.g. creating and running a Task) and less on the specific tools / dependencies used.

**Comment by vovtz** [comment]
I think you’re right, must’ve been a tendency to the OCD side in me ;) Although it could be OK to just now sync to the current state of affairs and get rid of the technical debt? 👼  I’ll add another commit to at least make it actually use version 3.10 and let you decide.

**Comment by AlanGreene** [comment]
I think it makes sense to stick with python 3.9 for now to be consistent with the other tutorials. Having consistency means future maintenance or rewrites should be simpler as the same / similar changes can be applied to them all without having to worry about differences due to dependency versions etc.

**Comment by vovtz** [comment]
Makes total sense. I changed this to only additionally pin the `python` image used in the sidecar as well (for complete consistency).

**Comment by AlanGreene** [comment]
That's great, thanks. Can you squash your commits and update the commit message to reference 3.9 instead then I think this is good to go 👍

**Comment by vovtz** [comment]
With the merge commits in there I’m unable to squash :( Created a new branch and PR instead.

**Pull request closed without merging**
