### PR TITLE
Sync missing docs from pipeline repo

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes
https://github.com/tektoncd/website/issues/125

- Migrating from v1alpha1 to v1beta1
- Pipeline metrics
- Variable substitution

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by popcor255** [comment]
The script is syncing the files but im not seeing the changes on my dev environment. 🤔

**Comment by AlanGreene** [comment]
You should see 'Pipeline Metrics' and 'Variable Substitution' in the Tasks and Pipelines section of the nav on `/docs/pipelines/`:
image

The beta migration guide is linked from 2 places on `/docs/pipelines/resources/`
1. the Note near the top of the page:
   > For Beta-supported alternatives to PipelineResources see **the v1alpha1 to v1beta1 migration guide**...
2. second last paragraph on the page

**Comment by popcor255** [comment]
oh okay. My bad! 👍 /lgtm

**Comment by AlanGreene** [comment]
@popcor255 `/lgtm` needs to be on its own line, can you give it another go? Thanks

**Pull request merged**
