### PR TITLE
Pipeline docs v0.22.0

### PR DESCRIPTION
**Pull request by pritidesai**
# Changes

Updating the docs on the website with the latest Pipeline release - v0.22.0

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by afrittoli** [comment]
@pritidesai could you rebase this? 🙏

**Comment by pritidesai** [comment]
> @pritidesai could you rebase this? 🙏

Done 👍  hopefully builds 🤞

**Comment by pritidesai** [comment]
the logs says:

```
9:18:05 AM: ERROR:root:No tag main found in <git.repo.base.Repo '/opt/build/repo/sync/.cache/pipeline/.git'>
9:18:05 AM: Makefile:3: recipe for target 'sync' failed
9:18:05 AM: make: *** [sync] Error 1
9:18:05 AM: ​
9:18:05 AM: ────────────────────────────────────────────────────────────────
9:18:05 AM:   "build.command" failed                                        
9:18:05 AM: ────────────────────────────────────────────────────────────────
9:18:05 AM: ​
9:18:05 AM:   Error message
9:18:05 AM:   Command failed with exit code 2: make preview-build
9:18:05 AM: ​
9:18:05 AM:   Error location
9:18:05 AM:   In build.command from netlify.toml:
9:18:05 AM:   make preview-build
9:18:05 AM: ​
9:18:05 AM:   Resolved config
9:18:05 AM:   build:
9:18:05 AM:     command: make preview-build
9:18:05 AM:     commandOrigin: config
9:18:05 AM:     environment:
9:18:05 AM:       - GCP_PROJECT
9:18:05 AM:       - REVIEW_ID
9:18:05 AM:       - HUGO_VERSION
9:18:05 AM:     publish: /opt/build/repo/public
9:18:05 AM: Caching artifacts
```

**Comment by afrittoli** [comment]
> the logs says:
> 
> ```
> 9:18:05 AM: ERROR:root:No tag main found in <git.repo.base.Repo '/opt/build/repo/sync/.cache/pipeline/.git'>
> 9:18:05 AM: Makefile:3: recipe for target 'sync' failed
> 9:18:05 AM: make: *** [sync] Error 1
> 9:18:05 AM: ​
> 9:18:05 AM: ────────────────────────────────────────────────────────────────
> 9:18:05 AM:   "build.command" failed                                        
> 9:18:05 AM: ────────────────────────────────────────────────────────────────
> 9:18:05 AM: ​
> 9:18:05 AM:   Error message
> 9:18:05 AM:   Command failed with exit code 2: make preview-build
> 9:18:05 AM: ​
> 9:18:05 AM:   Error location
> 9:18:05 AM:   In build.command from netlify.toml:
> 9:18:05 AM:   make preview-build
> 9:18:05 AM: ​
> 9:18:05 AM:   Resolved config
> 9:18:05 AM:   build:
> 9:18:05 AM:     command: make preview-build
> 9:18:05 AM:     commandOrigin: config
> 9:18:05 AM:     environment:
> 9:18:05 AM:       - GCP_PROJECT
> 9:18:05 AM:       - REVIEW_ID
> 9:18:05 AM:       - HUGO_VERSION
> 9:18:05 AM:     publish: /opt/build/repo/public
> 9:18:05 AM: Caching artifacts
> ```

Thanks, cleared the cache after the rebase solved the issue!

**Review by afrittoli — COMMENTED** [review]
/approve
/lgtm

**Comment by pritidesai** [comment]
thank you @afrittoli 🙏

**Pull request merged**
