### PR TITLE
[DO NOT MERGE] New tekton.dev experience

### PR DESCRIPTION
**Pull request by michaelawyu**
# Changes

This PR includes the new tekton.dev experience.

This PR is **in progress**. See the status tracker below.

## Tech

- [x] New tekton.dev experience with [Hugo](https://gohugo.io) and [Google Hugo Docsy Theme](https://github.com/google/docsy)
- [x] Support for multiple documentation versions
- [x] Support for content synchronization
- [x] Support for content curation
- [x] CI/CD workflow with Tekton for website generation
- [ ] Google Analytics Integration
- [ ] Google Custom Search Integration
- [x] Misc.

## Design

- [x] Cover
- [x] Asciinema cast
- [x] Partner logos
- [x] Manifesto
- [x] Interative tutorials (tekton.dev/try)
- [x] Version switcher
- [ ] Cookie usage notice for Google Analytics integration
- [x] Misc. 

## Contents

- [ ] Formatting contents in other sources of truth
- [ ] Interactive tutorials for launch

## Legal

- [x] Permission to use selected background image
- [ ] Permission to use partner logos
- [ ] Permission to integrate Google Analytics

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [N/A] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [Pending Changes] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by michaelawyu** [comment]
@bobcatfish

**Comment by michaelawyu** [comment]
Note:

- Partner logos are temporarily hidden until the approval goes through
- Launch-specific interactive tutorials are 66% completed:
    - _Getting Started_, _Tasks_ are completed
    - _Pipelines_ is in progress

**Comment by lucperkins** [comment]
@michaelawyu What was the reasoning behind moving away from Netlify for deployment? Without deploy previews it's quite difficult for viewers to have a sense of what the new site looks like.

**Comment by michaelawyu** [comment]
Hi @lucperkins ,

Actually I do not think there is a plan for moving away from the current platform; I used Firebase Hosting for now as this new experience still features a few changes that have not been approved for public use yet (Image Usage, Google Analytics integration, etc.) and I feel it is better to keep it within GCP/Firebase until everything gets ready.

michaelawyu

**Comment by bobcatfish** [comment]
Thanks for opening this @michaelawyu !!

Two initial requests:
1. It is very hard to review so many files b/c it is hard to tell which files have your modifications and which are static files that you did not change - is there some way we can reflect this with the folder structure, e.g. can all of the static files be put into one directory? If not it'd be great to have a list of which files are static and which aren't. 
2. Like @lucperkins pointed out, if it _is_ possible to host these files with netlify, can we make that work before we merge this? i.e. make it so that hte `netlify/tekton-dev/deploy-preview` GitHub check works

I have an idea how we could make 1) (and maybe also 2)?) way easier: do you think you could open a PR that commits only all the static files into the repo, and maybe makes it possible to view with netlify? Then we could review and merge that, then review your changes without having to review everything at once

Thanks again for getting this ball rolling!

image

**Comment by michaelawyu** [comment]
Closing the PR: As discussed with @bobcatfish this PR will be broken down into two separate ones.

**Pull request closed without merging**
