### PR TITLE
Create a Roadmap for the repo

### PR DESCRIPTION
**Pull request by sergetron**
# Changes

Creates a roadmap.md that describes the high-level roadmap for the website repo.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by jjasghar** [comment]
We should probably add a `tutorial` refresh/section update something like that. People have questions on how to do happy path things with Tekton, and we should gauge and build them.

**Comment by sergetron** [comment]
> We should probably add a `tutorial` refresh/section update something like that. People have questions on how to do happy path things with Tekton, and we should gauge and build them.

Added a section for tutorials, let me know if the wording is good.

**Comment by jjasghar** [comment]
@sergetron wunderbar!

**Comment by sergetron** [comment]
Anything else? If not, can we have an approval? :)

**Review by AlanGreene — APPROVED** [review]
The "getting started" and tutorial pieces seem to be very closely related. Would it make sense to combine them or reorder them in the list? Not a blocker, just something to consider.

This is a good start and we'll be updating it as we think of new items or make progress on any of these 👍 

/approve
/meow

**Comment by sergetron** [comment]
> The "getting started" and tutorial pieces seem to be very closely related. Would it make sense to combine them or reorder them in the list? Not a blocker, just something to consider.
> 
> This is a good start and we'll be updating it as we think of new items or make progress on any of these 👍
> 
> /approve
> /meow

The way I see it, the tutorials are quick step-by-step examples where a user accomplishes a specific thing to get hands-on with Tekton, whereas the "Getting Started" guide is an in-depth reference that discusses high-level concepts, pros and cons of different deployment scenarios and so on, so I think it makes sense to keep them separate. The guide and tutorials will definitely reference each other, too.

**Comment by afrittoli** [comment]
Great, thank you @sergetron! Looks good to me, in plain text to give a chance to others to add comments.

**Comment by AlanGreene** [comment]
I think folks have had enough time to comment and we can always update it later if needed.
Let's do this! :shipit: 

/lgtm

**Pull request merged**
