### PR TITLE
update hugo

### PR DESCRIPTION
**Pull request by Arhell**
# Changes

resolve https://github.com/tektoncd/website/issues/404

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

### CODE REVIEW

**Comment by afrittoli** [comment]
Thank you for this PR.
@geriom ok to do this or does it conflict with the docsy update you're working on?

**Review by geriom — APPROVED** [review]
Thank you!

@afrittoli There's not conflict with the changes I'm working on. We can merge it.

**Review by geriom — CHANGES_REQUESTED** [review]
@Arhell  Please rebase to include the change in #418, otherwise the build will fail.

**Review by Arhell — COMMENTED** [review]
Done

**Review by geriom — APPROVED** [review]
Thank you

**Pull request merged**
