### PR TITLE
Update Dashboard tutorial to latest versions

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

Update the Dashboard katacoda tutorial to use the latest releases:
- Dashboard 0.13.0
- Pipelines 0.20.0

Update screenshots to reflect the new design in recent dashboard versions.

The updated scenario can be previewed at https://katacoda.com/alangreene-tektoncd/scenarios/tekton-dashboard

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by AlanGreene** [comment]
Pipelines 0.20 released today and Dashboard 0.13 coming tomorrow. I'll update this then and mark for review again when it's ready.

/hold

**Comment by AlanGreene** [comment]
@jjasghar this is ready for a look now, thanks

/hold cancel

**Comment by jjasghar** [comment]
@AlanGreene awesome, on my list todo.

**Review by jjasghar — APPROVED** [review]
/lgtm

**Pull request merged**
