### PR TITLE
Add support for non text/markdown mime types

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Documentation may contain links to local files which are neither
text/markdown nor text/plain. Add support for those file by loading
them as binary (no decoding) and writing them as-is as binary in
the target location.

Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by afrittoli** [comment]
@AlanGreene @vdemeester @geriom 🙏 
This is needed for the chain docs.

**Review by AlanGreene — APPROVED** [review]
/lgtm

**Pull request merged**
