### PR TITLE
Update mermaid to fix Results data model diagram

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

Related https://github.com/tektoncd/results/pull/708
/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by avinal** [comment]
Instead of just updating the mermaid, we should bump the docsy version. This will bring more features and fixes along with the mermaid fix. It was updated a long time ago, given the website uses docsy 0.6 and the latest is 0.8 (https://github.com/google/docsy/releases/tag/v0.8.0)

**Comment by AlanGreene** [comment]
@avinal I agree that we should update docsy however I don't currently have time to work on this, especially given the warning about significant breaking changes in 0.7. If someone else has time to work on this in the near future that would be great.

In the meantime this is a small targetted fix to resolve a current issue on the website affecting our users.

**Comment by geriom** [comment]
>given the warning about significant breaking changes in 0.7. If someone else has time to work on this in the near future that would be great.

Yes, Docsy is now running on a newer version of bootstrap. I might have some time to look into this in late April, if someone wants to take a look sooner, I can share some useful links to help with the migration process.

**Review by geriom — APPROVED** [review]

**Review by avinal — APPROVED** [review]
Looks good to me

**Pull request merged**
