### PR TITLE
Add Triggers v0.23.0

### PR DESCRIPTION
**Pull request by khrm**
Add the docs for Triggers v0.23.0

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by AlanGreene** [comment]
Typo in the commit message, and description. Should be v0.23.0

**Comment by AlanGreene** [comment]
Build is failing due to mismatch in config for the Dashboard docs, looks like your PR is based on an older commit. Please rebase to pick up the latest config.

**Review by khrm — COMMENTED** [review]
/retest

**Review by AlanGreene — APPROVED** [review]
Thanks @khrm 
/lgtm

**Pull request merged**
