### PR TITLE
Add missing CLI releases to the docs 📖

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

We missed some updates when releasing the cli, fixing this for current releases.

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/cc @afrittoli
/cc @tektoncd/cli-maintainers 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by piyush-garg — APPROVED** [review]
/lgtm

**Comment by chmouel** [comment]
We need to add this step to the release process document

/lgtm

**Review by afrittoli — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
