### PR TITLE
Renaming branches: handling triggers and CLI repository

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

Changing links to any reference to tektoncd/triggers.

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/hold
/cc @afrittoli @bobcatfish @ImJasonH 

Related to tektoncd/plumbing#681

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by ImJasonH — APPROVED** [review]

**Comment by afrittoli** [comment]
> same as the CLI one, it'll need a new commit pushed to trigger the netlify build
> /approve

I can trigger it manually from netlify

**Comment by afrittoli** [comment]
This one fails because of CLI and the CLI one fails because of this.
You'll need to merge the two PRs into one for it to work.
@vdemeester

**Review by afrittoli — COMMENTED** [review]
Thank you!
/lgtm

**Pull request merged**
