### PR TITLE
Add triggers v0.17.1, v0.18.0 and v0.19.0

### PR DESCRIPTION
**Pull request by khrm**
Add the docs for triggers v0.18.0 & v0.19.0, and updated v0.17.0 to v0.17.1

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by afrittoli** [comment]
@khrm I think this may need to be rebased for CI to pass 🙇

**Comment by khrm** [comment]
@afrittoli 

Getting `1:00:42 PM: ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/opt/buildhome/python3.7/lib/python3.7/site-packages/markupsafe/__init__.py)
`

**Review by afrittoli — COMMENTED** [review]
/lgtm

**Pull request merged**
