### PR TITLE
Add the images folder in triggers sync config

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Pull in SVG images from triggers docs/images into the main docs
folder, so that we can display it correctly.

Partially addresses #340

Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by vovtz** [comment]
/reopen

Apparently didn’t get any attention, didn’t get approved nor denied

**Comment by dibyom** [comment]
@afrittoli @AlanGreene @geriom does it make sense to reopen this to fix #453 and #340

**Comment by vovtz** [comment]
/remove-lifecycle stale

Just needs a little bit of attention (I would do it myself if I had a bit of knowledge about the setup of the docs).

**Comment by geriom** [comment]
I spent most of the day trying to figure this out. So far no success but I noticed a few things:

1. The exact line that breaks the links is 299 in `sync.py`. The statement `if fq_path in local_files:` checks whether relative links point to valid cloned files, if not they are turned into (incorrect) absolute links. At first I thought the error was in this giving false negatives, but..
2. This works correctly in one instance. Opening the the `main` tag in the vault docs: http://localhost:8888/vault/triggers-main/ works fine. 
3. I checked the other versions of the same docs and none of them have the `images` folder other than `main`. So my guess is that the sync script is not handling correctly all the tags. There are inconsistencies in other repos too.

I will look into this some more tomorrow.

**Pull request closed without merging**
