### PR TITLE
Add Triggers v0.22.0

### PR DESCRIPTION
**Pull request by khrm**
Add the docs for Triggers v0.22.0

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by AlanGreene** [comment]
@khrm There's a typo in the commit message, should be 0.22 instead of 0.21

**Review by khrm — COMMENTED** [review]
/retest

**Comment by AlanGreene** [comment]
@khrm the build is failing because there's `No tag or branch release-v0.22.x found` in the triggers repo.

**Comment by khrm** [comment]
@AlanGreene Fixed that.

**Review by AlanGreene — APPROVED** [review]
Thanks @khrm 
/lgtm

**Pull request merged**
