### PR TITLE
Add pipelines v0.21.0

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Add pipelines v0.21.0

Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

/kind documentation

### CODE REVIEW

**Comment by afrittoli** [comment]
@tektoncd/website-maintainers 🙏

**Comment by jerop** [comment]
@afrittoli what do you think about adding this step to [the release cheatsheet](https://github.com/tektoncd/pipeline/blob/master/tekton/release-cheat-sheet.md) after updating the catalog test infrastructure?

I can open a PR to add it but wanted to confirm first that this is not something that website maintainers want to do themselves

**Comment by afrittoli** [comment]
> @afrittoli what do you think about adding this step to [the release cheatsheet](https://github.com/tektoncd/pipeline/blob/master/tekton/release-cheat-sheet.md) after updating the catalog test infrastructure?
> 
> I can open a PR to add it but wanted to confirm first that this is not something that website maintainers want to do themselves

Thank you! I made the PR already some time ago: https://github.com/tektoncd/pipeline/pull/3688

**Review by AlanGreene — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]
/lgtm

**Pull request merged**
