### PR TITLE
add operator v0.71.x docs

### PR DESCRIPTION
**Pull request by jkandasa**
# Changes

* adds operator v0.71.x documentation
* marked `LTS` releases

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by jkandasa** [comment]
cc @AlanGreene @vdemeester

**Comment by vdemeester** [comment]
@jkandasa 0.71.x is still unreleased, right ?

**Comment by jkandasa** [comment]
> @jkandasa 0.71.x is still unreleased, right ?
Yes, not released yet. 

@AlanGreene Sure, I will update the doc and LTS details and let you know.

**Comment by jkandasa** [comment]
@vdemeester @AlanGreene operator `v0.71.0` is released and I have updated the supported matrix on https://github.com/tektoncd/operator, and on releases added string `LTS`

In this PR, I have included new field called `supportEnds`, That will be helpful to remove unsupported versions in the future (without referring operator repository). Please let me know, if `supportEnds` doesn't look good, I can remove from this PR.

**Review by AlanGreene — APPROVED** [review]

**Pull request merged**
