### PR TITLE
Fix kind of resource definition

### PR DESCRIPTION
**Pull request by thomasboni**
# Changes

Fix an error in Getting started section of the documentation (wrong name of resource kind)

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by thomasboni** [comment]
About EasyCLA: sorry, but I haven't time to review and sign the Individual Contributor License Agreement v2. Feel free to close this PR if this step is mandatory.

**Comment by AlanGreene** [comment]
Thanks for the PR @thomasboni. Yes we do require an authorised CLA for contributions.

**Review by afrittoli — COMMENTED** [review]
Thank you!
/approve
/lgtm

**Comment by afrittoli** [comment]
Oh, I didn't realise about the CLA issue.
@thomasboni thanks for catching this and proposing a PR. 
If you cannot sign the CLA, perhaps one of the @tektoncd/website-maintainers can resubmit the PR.

**Comment by thomasboni** [comment]
Hi @afrittoli, I just signed the CLA

**Comment by afrittoli** [comment]
Thank you!

**Pull request merged**
