### PR TITLE
Speed up things with parallel processing

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Most of the time required for a sync is spent in two tasks:
- wget of all the original files
- validating the URLs with urlopen().read()

Running those two tasks in parallel greatly reduces the
processing time. This will be even more relevant when syncing
files from multiple releases.
# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by afrittoli** [comment]
This is based on some simple profiling of the `sync` script:
```
I tried to profile a sync  - these are the top items ordered by cumtime
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    230/1    0.002    0.000  102.433  102.433 {built-in method builtins.exec}
        1    0.000    0.000  102.433  102.433 sync.py:21(<module>)
        1    0.000    0.000  102.068  102.068 app.py:269(run)
        1    0.000    0.000  102.064  102.064 app.py:230(_run_main)
        1    0.000    0.000  102.064  102.064 sync.py:262(sync)
        1    0.000    0.000  102.014  102.014 sync.py:163(download_resources_to_project)
        3    0.000    0.000   83.485   27.828 sync.py:64(transform_text)
        3    0.014    0.005   83.484   27.828 sync.py:83(set_lines)
     8687    0.032    0.000   83.429    0.010 sync.py:72(transform_links)
      425    0.003    0.000   78.243    0.184 sync.py:106(is_url)
    13872    0.034    0.000   75.343    0.005 socket.py:655(readinto)
    13872    0.031    0.000   75.286    0.005 ssl.py:1230(recv_into)
    13872    0.020    0.000   75.249    0.005 ssl.py:1090(read)
    13872   75.227    0.005   75.227    0.005 {method 'read' of '_ssl._SSLSocket' objects}
      454    0.001    0.000   74.021    0.163 request.py:139(urlopen)
  490/454    0.004    0.000   74.016    0.163 request.py:506(open)
  516/442    0.001    0.000   73.994    0.167 request.py:495(_call_chain)
      224    0.001    0.000   73.907    0.330 request.py:535(_open)
      224    0.001    0.000   73.906    0.330 request.py:1392(https_open)
      224    0.005    0.000   73.905    0.330 request.py:1309(do_open)
     5047    0.006    0.000   53.343    0.011 {method 'readline' of '_io.BufferedReader' objects}
      224    0.003    0.000   53.226    0.238 client.py:1303(getresponse)
      224    0.004    0.000   53.214    0.238 client.py:300(begin)
      224    0.005    0.000   53.051    0.237 client.py:267(_read_status)
      263    0.004    0.000   22.728    0.086 client.py:447(read)
     1547    0.111    0.000   21.894    0.014 {method 'read' of '_io.BufferedReader' objects}
     1239    0.003    0.000   21.814    0.018 client.py:605(_safe_read)
      224    0.001    0.000   18.539    0.083 client.py:1252(request)
      224    0.003    0.000   18.538    0.083 client.py:1257(_send_request)
        3    0.001    0.000   18.529    6.176 sync.py:138(download_files)
```
It shows that lot of the time is spend in the `is_url` method

**Comment by AlanGreene** [comment]
Parallelisation definitely makes sense 👍 especially as you said when adding multiple versions for each project.
/approve

For `is_url`, rather than making a GET request and reading the response body could we get away with just making a HEAD request and checking the status code?

**Comment by popcor255** [comment]
> Parallelisation definitely makes sense +1 especially as you said when adding multiple versions for each project.
> /approve
> 
> For `is_url`, rather than making a GET request and reading the response body could we get away with just making a HEAD request and checking the status code?

We could also, just do some text validation for is_url and check the url status on the test. However, I think @AlanGreene is better. +1

**Comment by afrittoli** [comment]
> Parallelisation definitely makes sense 👍 especially as you said when adding multiple versions for each project.
> /approve
> 
> For `is_url`, rather than making a GET request and reading the response body could we get away with just making a HEAD request and checking the status code?

Yeah, that would be a nice improvement.

**Pull request merged**
