### PR TITLE
Add Tekton home page in Japanese

### PR DESCRIPTION
**Pull request by takoh-yuuichiro**
# Changes

- Add Tekton home page texts in Japanese
- Add Japanese translation to
    - ja.toml
    - privacy-notice-ja.html
    - manifesto-ja.html
    - partners-alternate-ja.html
- Add Japanese language settings
- Add a language selector for the navigation bar

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by kobaji** [comment]
Hi @afrittoli this is @kobaji working with @takoh-yuuichiro 
Thank you for reviewing this PR.
This is related to an issue #243 and I believe worth deepening understandings for Japanese people.
We are happy to maintainer or improve this translation.

Thank you again for reviewing this PR.

**Comment by afrittoli** [comment]
Hello @takoh-yuuichiro - thank you for this PR!
It would be great to have our home page in Japanese.
My only concern is that I'm not able to review the PR - since I cannot read Japanese 🙏 
I could try with google translate :)

**Comment by takoh-yuuichiro** [comment]
Hello @afrittoli - thank you for your reply.
We are very glad that you will try to review this PR by translating the home page in Japanese.
Please let us know if you find anything.

Thank you again for your cooperation.

**Comment by kobaji** [comment]
Thank you very much @afrittoli for your kind comment.

I am very grateful that you would try to review the translation.

We are also concerned if the source codes what we created are appropriate because this feature enables translating multi languages asides from French, Italy, Chinese, and so on. And that's why we would be very grateful if you kindly reviewed the source codes.

Thank you again for your kind help!!

**Comment by kobaji** [comment]
@afrittoli Thank you very much for considering this PR.
If we should explain in online meeting such as [documentation working group](https://github.com/tektoncd/community/blob/main/working-groups.md#documentation), I will be adjusting a schedule (My only concern is that the working group would be held at midnight in Japan haha).

I also wish translation like google translate does work (If there were some Japanese speakers except us in Tekton community, it would be much easier :) ).

**Comment by AlanGreene** [comment]
Apologies for the delay in getting back to you. We resumed the Tekton Docs & Website working group last week after a long break, and discussed this PR at today's meeting.

We're not currently planning to provide translations of the home page or other content. We may revisit this at some point in future if there's more interest, but it would require a number of changes:
- we would need a group who can commit to maintaining translations for each language
- we would also need to change how the translated content is used to avoid the need to duplicate the structure of each affected page or fragment. The current approach makes it much more difficult to make changes to the style, structure, layout, etc. as the same changes would need to be made for each language
- we would need a robust process to ensure translations are completed in a timely manner to avoid content becoming stale or potentially providing conflicting information in different languages

Thanks again @takoh-yuuichiro and @kobaji for your contribution 😸 
Closing the PR for now.

**Pull request closed without merging**
