### PR TITLE
Fix css from breaking for different browsers.

### PR DESCRIPTION
**Pull request by popcor255**
# [Changes](https://5ec96cb12396fe6795c23749--determined-jackson-ad4f96.netlify.app/)
### Changed max-width from certain elements:

The banner for cd foundation and partners are off center after a certain size of 1739px. As a user this breaks the flow and decreases the usuability of the website. Reference: [#113](https://github.com/tektoncd/website/issues/113)

### Changed Padding Sizes:

The padding for the banners on the tekton webpage had incorrect max-widths and some strange padding.
As a user these changes improve the flow of the website.

### Add bg color to wrapper below container:

The copyright on the footer is not visible on IOS because rendering on IOS mobile devices are different and causes the style to overridden on IOS devices. Added the class to an one element below to fix this issue.

## Before:
(Did not include images from IOS device)

image

image

## After:
(Did not include images from IOS device)

image
image

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by afrittoli** [comment]
Thanks for this!
I checked the deploy from the CI Job. It still looks ok on firefox and chrome, both on laptop and mobile phone. I don't have an iOS device to check there. I tested on Safari on MacOS, and while it looks better, there still are issues on the bottom left and right:

image

**Comment by popcor255** [comment]
Oof. I'll fix that.

**Comment by popcor255** [comment]
This is what Tekton.dev looks like on iOS.

**Pull request merged**
