### PR TITLE
Enable netlify-plugin-checklinks

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Add the netlify-plugin-checklinks plugin to check for broken
links on deploy.

Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [-] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by afrittoli** [comment]
Searching for broken fragments in the logs, it looks like there's quite a few of them:
```
$ grep "expected: id=" /tmp/log | awk '{ print $5 }' | sort | uniq
id="accessing-steps-exitcode-in-subsequent-steps"
id="adding-breakpoints"
id="check"
id="configuring-execution-results-at-the-pipeline-level"
id="configuring-execution-results-at-the-task-level"
id="description"
id="disabling-tektons-built-in-auth"
id="example-of-reusing-a-task"
id="example-of-specifying-a-service-account"
id="guard-task-execution-using-whenexpressions"
id="interceptors"
id="outputs"
id="parameters"
id="passing-one-tasks-results-into-the-parameters-or-when-expressions-of-another"
id="pipelineresources-and-catalog-tasks"
id="pipelineruns"
id="resources"
id="service-account"
id="specifiying-the-kubernetes-service-account"
id="specifying-target-labels"
id="specifying-trigger-groups"
id="steps"
id="substituting-volume-names-and-paths"
id="taskruns"
id="using-workspace-variables-in-taskruns"
id="variable-substitution"
id="why-arent-pipelineresources-in-beta"
```

I started opening one issue on triggers: https://github.com/tektoncd/triggers/issues/1258

**Comment by afrittoli** [comment]
It looks like with this configuration the plugin is executed but the failures are ignored, so the build passes.
I would propose to merge this PR so we can always have an up to date list of broken things. 
We might be able to enforce the check at some point - the problem with using branch references though is that they may change and so the content may change without going through a CI job. Or perhaps the check would be executed during the nightly deploy too and prevent broken links from being deployed to the live site?

**Review by AlanGreene — APPROVED** [review]
Thanks @andrea, this is useful to have even if we're not going to block deployment.

Where can I find the results of the plugin?

**Comment by AlanGreene** [comment]
I can see the logs from the preview link now 👍  We can keep an eye on this and start driving the issues towards zero
/lgtm

**Pull request merged**
