### PR TITLE
Remove sbwsg from OWNERS

### PR DESCRIPTION
**Pull request by sbwsg**
# Changes

This PR removes me from OWNERS file.

It made sense for me to be in OWNERS while we were releasing Beta but I'm not keeping up with current website planning & work so don't want to be blocking reviews.

### CODE REVIEW

**Comment by bobcatfish** [comment]
In pipeline/OWNERS we have an "alumni" section, would probably be nice to have here as well? https://github.com/tektoncd/pipeline/blob/078f08168b2cc3f60ccf7c4acc63c666350eb6b0/OWNERS#L12

**Comment by sbwsg** [comment]
> In pipeline/OWNERS we have an "alumni" section, would probably be nice to have here as well? https://github.com/tektoncd/pipeline/blob/078f08168b2cc3f60ccf7c4acc63c666350eb6b0/OWNERS#L12

Good call; I've added that here as well, cheers!

**Comment by bobcatfish** [comment]
Thanks @sbwsg !

/lgtm
/approve
/meow

**Comment by bobcatfish** [comment]
i feel like the meow plugin has been improving lately

**Pull request merged**
