### PR TITLE
fix small jump on open close dropdown

### PR DESCRIPTION
**Pull request by Arhell**
# Changes

resolve https://github.com/tektoncd/website/issues/406
copied sidebar-tree.html and small fix

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by afrittoli** [comment]
Thanks @Arhell - I'm not sure I see the issue and the difference in the fix. 
@geriom is working on pulling in a new version of docsy - I wonder if it would be worth fixing such issues upstream instead or if a fix may already be available there?

**Comment by Arhell** [comment]
> Thanks @Arhell - I'm not sure I see the issue and the difference in the fix. @geriom is working on pulling in a new version of docsy - I wonder if it would be worth fixing such issues upstream instead or if a fix may already be available there?

In the new version there is no such problem, he corrected it in due time. If needed, I can help with the update and make a gitsubmodule

**Comment by geriom** [comment]
Thanks @Arhell. The updated docsy preview is live now here: https://docsy-update--tekton.netlify.app/docs/

Let me know if you something missing.

**Comment by Arhell** [comment]
> Thanks @Arhell. The updated docsy preview is live now here: https://docsy-update--tekton.netlify.app/docs/
> 
> Let me know if you something missing. You can open PRs against the `update_docsy` branch.



> Thanks @Arhell. The updated docsy preview is live now here: https://docsy-update--tekton.netlify.app/docs/
> 
> Let me know if you something missing. You can open PRs against the `update_docsy` branch.

Thank you, no, I looked, everything is ok.
I would only recommend updating to version 0.4.0
https://github.com/tektoncd/website/commit/e12f8507e2cfbc4424ce755682c5d72573c0731b#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R5

https://github.com/tektoncd/website/commit/e12f8507e2cfbc4424ce755682c5d72573c0731b#diff-3295df7234525439d778f1b282d146a4f1ff6b415248aaac074e8042d9f42d63R2

you can also tell me how to update these versions, I want to support the site in the future, thanks

I know how to update via git, but unfortunately not via go

**Comment by geriom** [comment]
> you can also tell me how to update these versions, I want to support the site in the future, thanks
> 
> I know how to update via git, but unfortunately not via go

I will document the updating process once we merge those changes into main. 

Glad to have you as contributor! If you want, you can [join the Slack channel and the mailing list ](https://github.com/tektoncd/community/blob/main/contact.md#slack), and the [weekly Working Group meeting](https://github.com/tektoncd/community/blob/main/working-groups.md#documentation) to get more involved in community discussions.

**Pull request closed without merging**
