### PR TITLE
update footer to include standard LF copyright notice

### PR DESCRIPTION
**Pull request by danlopez00**
# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ Y] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ Y] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by bobcatfish** [comment]
I think this is out of date and will need to be redone

**Comment by caniszczyk** [comment]
this is fairly important for our legal team, @danlopez00 please see this to completion

**Comment by vdemeester** [comment]
@caniszczyk closing this doesn't mean we won't see this to completion :wink: It just needs it's probably better to start from a fresh checkout :wink:

**Comment by skaegi** [comment]
/close
This was handled in #52

**Pull request closed without merging**
