### PR TITLE
Add docs for pipeline v0.18.0

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Add the new version and add some docs that were previously excluded:
- deprecations
- runs
- tekton bundles contract

Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

/kind documentation

/cc @pritidesai @vdemeester @bobcatfish

### CODE REVIEW

**Comment by bobcatfish** [comment]
Seems like netlify isn't happy with something! Which is weird since you're pretty much only changing config 🤔  i tried hitting "redeploy"

but anyway netlify/tekton/deploy-previewRequired is a required check so should be safe to:

/approve
/lgtm

**Comment by bobcatfish** [comment]
```
10:46:28 AM: ERROR:root:No tag v0.18.0 found in <git.repo.base.Repo '/opt/build/repo/sync/.cache/pipeline/.git'>
```

hm

**Comment by afrittoli** [comment]
Uhm... it looks like netlify is re-using the host for the deploy, I see from the logs it finds a cache of the repos.
I'll add an option to force updating the cache (or deleting them).

**Comment by afrittoli** [comment]
Uhm, I tried to fix the code quickly, but I need to check with more time tomorrow.

**Comment by afrittoli** [comment]
> Uhm, I tried to fix the code quickly, but I need to check with more time tomorrow.

:tada: I finally got it working. Multiprocess cannot pickle a local/partial function, I had to use `starmap` :]

**Comment by pritidesai** [comment]
Screen Shot 2020-11-10 at 1 57 17 PM

/lgtm

**Comment by bobcatfish** [comment]
> Multiprocess cannot pickle a local/partial function, I had to use starmap :]

XD I like python ⭐  🥒

**Pull request merged**
