### PR TITLE
Reorganize the left navigation menu

### LINKED ISSUE #338: Reorder the left-hand side navigation structure
### Feature request

The current structure does not follow a logical order. Restructure it to make it more user friendly. More details can be found in the roadmap updates in #337, which in turn is based on our discussions in the Docs WG.

### PR DESCRIPTION
**Pull request by geriom**
# Changes

To match the structure agreed on the [documentation  plan](https://github.com/tektoncd/website/blob/main/roadmap.md), 
this CL moves the imported documentation to its own section, "Reference".

-  Netlify file updated to redirect old URLs to the new location.

-  Dockerfile and docker-compose files updated to use nelitfy to run
   the site and mount the volumes in the correct locations.

-  Sync script updated to match the new structure.

-  New folders that will contain the API, and Installation documents are
   created as placeholders. To be populated later.

-  `.gitignore` updated to exclude new directories.

## Navigation comparison

| New   |      Old     |
|----------|:-------------:|
|  Screenshot from 2022-06-22 11-14-26 | Screenshot from 2022-06-22 11-10-11   |

/closes #338 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by geriom** [comment]
It seems I have to update the unit tests too. Added "work in progress" till it passes all the checks. Feel free to review what's currently here.

**Review by afrittoli — COMMENTED** [review]
Thanks, the content looks great! A couple of small things:

- the left menus are expanded by default, I think it would be good to have them collapsed by default to benefit from the new lean structure
- perhaps before adding an installation section in there we should make sure we can populate it correctly through the sync?
- The links below the content in [reference](https://deploy-preview-395--tekton.netlify.app/docs/reference/) are not ok. The first one is text without a link, and then there seem to be a few missing ones. This is not new, but perhaps it's more visible with the new structure? It used to be in https://tekton.dev/docs/. Anyways, something we can fix in separate PRs (and probably in the relevant repos).
- Python tests need to be updated to match the changes in the sync script. I wonder however if we really need to change the sync script. It may be possible to address this by altering the config instead. My concern is that if we want to pull installation configuration in other folders we won't be able to do it with this change

**Comment by geriom** [comment]
/lifecycle frozen

I'll do my best to come back to this before the end of the year. Either updating the sync script or exploring a different approach.

**Comment by geriom** [comment]
Attempting a different approach in #502 Closing this one.

**Pull request closed without merging**
