### PR TITLE
Add the past 4 versions for pipeline, triggers and CLI

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Set the latest version of each component as the current one, add
everything else, including master, to the vault.
Remove the _index.md files that are brought in via sync.

Fix the version switcher to display latest release.
When an older version is selected, we still want to be able
to select the latest version. Alter the version switcher to
allow for that.

Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

/kind misc

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/meow
:tada:

**Comment by AlanGreene** [comment]
Overall this looks good. We could make improvements to the styling of the dropdown to make it more obvious what's clickable / expandable etc., but at least having the previous versions available is a great start 🎉

**Comment by afrittoli** [comment]
> Overall this looks good. We could make improvements to the styling of the dropdown to make it more obvious what's clickable / expandable etc., but at least having the previous versions available is a great start 🎉

Thanks!
I don't really have a clue at javascript, so if someone wants to volunteer for improving the look of it it'd be great.
Perhaps you could file an issue with your suggestions, so that we don't lose track :)

**Comment by AlanGreene** [comment]
Most of my comments from https://github.com/tektoncd/website/issues/130#issuecomment-634763003 have already been addressed by this PR (add latest to the version switcher) and previous changes. Happy to open a new issue for the remaining suggestions so they don't get lost 👍

**Comment by bobcatfish** [comment]
I'm very happy to merge this as-is and iterate on it!

I think even just being able to see what version we're currently displaying docs for is a huge win:

image

My initial thoughts (feel free to ignore):

1. Click to expand in this menu feels a bit weird to me:
image

image
Is it crazy to leave it expanded by default?

2. Mentioned earlier today but esp. if we want more than 4 versions in the long run, i think a drop down might make more sense vs trying to fit them all into that menu (maybe we open an issue and leave for someone to help us out with)

**Comment by afrittoli** [comment]
@bobcatfish Thanks for the feedback. I think the current menu may be ok to have open by default, but it will become too much as we add more releases.

Ideally I would like to:
- remove links to releases on github from that menu, and put that link somewhere else
- make the link to master docs a single link that points to the combined docs of all projects on master. BTW if we keep master we should eventually do something like a nightly deployment so that it is up to date. If I'm not mistaken we only deploy on merged PRs today
- turn the list of versions in something like a dropdown box 

I'd prefer to start merging this PR though - before doing any of that.

**Comment by afrittoli** [comment]
For nightly deployment: https://github.com/tektoncd/website/pull/192

**Comment by bobcatfish** [comment]
/lgtm

Thanks again @afrittoli !

**Pull request merged**
