### PR TITLE
Accessibility add alt to images

### PR DESCRIPTION
**Pull request by Arhell**
# Changes

resolve https://github.com/tektoncd/website/issues/396

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by afrittoli — COMMENTED** [review]
Nice, thank you!!
The PR is marked as draft, but I definitely approve of this work :)

**Comment by Arhell** [comment]
cc @afrittoli

**Comment by Arhell** [comment]
cc @vdemeester

**Review by AlanGreene — APPROVED** [review]
Thanks @Arhell
/lgtm

**Pull request merged**
